version: '3'
services:
  server:
    command: /bin/bash ./bin/prod.sh
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: server
    env_file: .env
    volumes:
      - ./server:/app
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always
  db:
    image: postgres:11.0
    container_name: db
    restart: always
    expose:
      - "5432"
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data