# Generated by Django 3.0.8 on 2020-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200712_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, default=None, verbose_name='Юзернейм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID пользователя социальной сети'),
        ),
    ]
