# Generated by Django 3.0.8 on 2020-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200712_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(verbose_name='Юзернейм'),
        ),
    ]
