# Generated by Django 3.0.8 on 2020-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_gasstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
