# Generated by Django 3.0.8 on 2020-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200718_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='search_radius',
            field=models.PositiveIntegerField(default=4, verbose_name='Радиус поиска'),
        ),
    ]
