# Generated by Django 3.0.8 on 2020-07-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_active_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasstation',
            old_name='gps',
            new_name='location',
        ),
    ]
