# Generated by Django 3.0.8 on 2020-07-28 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_fuelprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelprice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
